// <auto-generated />
namespace s00164548Week6Lab2.Migrations.ClubModelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialiseClubs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialiseClubs));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101145350_InitialiseClubs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
